# Generated by Django 5.2.7 on 2025-10-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Be_men_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                default="default.png", null=True, upload_to="profiles/"
            ),
        ),
    ]
