# Generated by Django 5.2.7 on 2025-10-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Be_men_user", "0004_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="product",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="user",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Wishlist",
        ),
    ]
