# Generated by Django 5.2.7 on 2025-10-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Be_men_user", "0005_remove_order_product_remove_order_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
    ]
