# Generated by Django 5.2.7 on 2025-10-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Be_men_admin", "0001_initial"),
        ("Be_men_user", "0005_remove_order_product_remove_order_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="ProductCategory",
        ),
    ]
