# Generated by Django 5.2.7 on 2025-10-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_order_cancelled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="return_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="returned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("PROCESSING", "Processing"),
                    ("SHIPPED", "Shipped"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("RETURN_PENDING", "Return Pending"),
                    ("RETURNED", "Returned"),
                ],
                default="PROCESSING",
                max_length=20,
            ),
        ),
    ]
